name: Integration Tests
 
env:
  DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DATABASE: ${{ secrets.DATABASE }}
 
on:
  pull_request:
    branches:
      - main
      
jobs:
  integration-test:
    runs-on: ubuntu-latest
 
    steps:
      - name : Install MySQL
        run: |
          sudo apt-get update
          sudo apt install mysql-server
          sudo systemctl start mysql
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATABASE }};"
 
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          
      - name: Install Dependencies
        run: npm install
 
      - name: Run Tests
        run: npm test
